/* eslint-disable import/no-anonymous-default-export */
export default {
  AUTH_SET_ACCESS_TOKEN: "APP_AUTH_SET_ACCESS_TOKEN",
  AUTH_LOGOUT: "APP_AUTH_LOGOUT",
  AUTH_ERROR:"APP_AUTH_ERROR",
  AUTH_VERIFY:"AUTH_VERIFY",
  AUTH_LOGIN:"AUTH_LOGIN",

  TABLE_SET_LOADING: 'APP_TABLE_SET_LOADING',
  TABLE_SET_DATA: 'APP_TABLE_SET_DATA', 
  TABLE_SET_TOTAL: 'APP_TABLE_SET_TOTAL',
  TABLE_ERROR: 'APP_TABLE_ERROR', 
  TABLE_FETCH_DATA: 'APP_TABLE_FETCH_DATA',
}