export default {
  AUTH_LOGIN: 'KIPOD_AUTH_LOGIN',
  GET_PERSON_FACE_IN: 'KIPOD_GET_PERSON_FACE_IN',
  GET_PERSON_FACE_SET_DATA: 'KIPOD_GET_PERSON_FACE_SET_DATA',
  GET_PERSON_FACE_OUT: 'KIPOD_GET_PERSON_FACE_OUT'
}